# Generated by Django 5.2.5 on 2025-09-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_date_added_alter_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'نو'), ('old', 'دست دوم')], default='new', max_length=3),
        ),
    ]
