# Generated by Django 5.2.5 on 2025-09-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_comment_is_active_comment_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_calming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_educational',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_motivational',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_uplifting',
            field=models.BooleanField(default=False),
        ),
    ]
